[package]
name = "bang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8"
crossterm = "0.24"
shell-words = "1.1.0"
tui = "0.18"
